# DST Training Data Source Configuration

name: "dst_training"

# Frame-level training data paths
# dst_data_path: custom/outputs/dst_generated/proassist_label/2025-11-06/17-02-11_gpt-4o_proassist_50rows  # From DST generator
dst_data_path: custom/outputs/dst_generated/proassist_label/2025-11-12/10-10-29_gpt-4o_proassist_50rows
raw_data_path: data/proassist/processed_data

datasets:
  - assembly101
  # - ego4d
  # - egoexolearn
  # - epickitchens
  # - holoassist
  # - wtag

# Frame-level data structure (training specific)
fps: 2
max_seq_len: 4096
reserved_seq_len: 128



