[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "dst-data-builder"
version = "0.0.1"

[tool.setuptools]
package-dir = {"" = "custom/src"}
packages = ["dst_data_builder", "dst_data_builder.gpt_generators"]
