# Simple DST Generator Configuration

defaults:
  - data_source: proassist
  # - generator: batch
  - generator: single
  - model: gpt4o
  # - model: claude4_5

max_retries: 2
# Logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

exp_name: 5000rows
# Hydra configuration
hydra:
  run:
    dir: custom/outputs/dst_generated/${now:%Y-%m-%d}/${now:%H-%M-%S}_${model.log_name}_${data_source.name}_${exp_name}
