# DST Training Configuration
defaults:
  - model: dst_smolvlm2
  - data_source: dst_training
  - input_style: proassist
  - _self_

# Output directory
output_dir: custom/outputs/prospect/dst_training/${now:%Y-%m-%d}/${now:%H-%M-%S}_${model.log_name}

project_root: /u/siddique-d1/adib/ProAssist
raw_data_root: ${project_root}/data/proassist/processed_data
# Experiment name
exp_name: "dst_training_assembly101"

# Hydra configuration
hydra:
  run:
    dir: ${output_dir}
