name: /u/siddique-d1/adib/ProAssist/.venv
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - expat=2.7.1
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - packaging=25.0
  - pathos=0.3.0
  - pip=25.2
  - pox=0.3.6
  - ppft=1.7.7
  - pthread-stubs=0.3
  - pytest=8.4.2
  - python=3.10.18
  - readline=8.3
  - sqlite=3.50.2
  - tk=8.6.15
  - tomli=2.2.1
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - abnf==2.2.0
      - absl-py==2.3.1
      - accelerate==1.11.0
      - addict==2.4.0
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.0
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.11.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - astunparse==1.6.3
      - async-lru==2.0.5
      - async-timeout==5.0.1
      - attrs==25.4.0
      - av==15.1.0
      - babel==2.17.0
      - backoff==2.2.1
      - backports-asyncio-runner==1.2.0
      - beautifulsoup4==4.14.2
      - bitsandbytes==0.48.2
      - bleach==6.2.0
      - boto3==1.40.46
      - botocore==1.40.46
      - brotli==1.1.0
      - certifi==2025.10.5
      - cffi==2.0.0
      - chardet==5.2.0
      - charset-normalizer==3.4.4
      - cint==1.0.0
      - click==8.3.0
      - cloudpickle==3.1.1
      - cmake==4.1.0
      - colorama==0.4.6
      - comm==0.2.3
      - contourpy==1.3.2
      - coverage==7.11.3
      - cryptography==46.0.3
      - cycler==0.12.1
      - dataclasses-json==0.6.7
      - datasets==2.21.0
      - debugpy==1.8.17
      - decorator==5.2.1
      - defusedxml==0.7.1
      - dill==0.3.8
      - diskcache==5.6.3
      - distro==1.9.0
      - docker-pycreds==0.4.0
      - docopt==0.6.2
      - editdistance==0.6.2
      - ego4d==1.7.3
      - einops==0.7.0
      - et-xmlfile==2.0.0
      - eval-type-backport==0.2.2
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - fairscale==0.4.0
      - fastapi==0.118.0
      - fastjsonschema==2.21.2
      - ffmpy==0.6.1
      - fickling==0.1.4
      - filelock==3.20.0
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - fqdn==1.5.1
      - frozenlist==1.8.0
      - fsspec
      - gast==0.6.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-pasta==0.2.0
      - gql==4.0.0
      - gradio==5.49.0
      - gradio-client==1.13.3
      - graphql-core==3.2.7
      - graphviz==0.21
      - groovy==0.1.2
      - grpcio==1.76.0
      - h11==0.16.0
      - h5py==3.15.1
      - hf-xet==1.2.0
      - hjson==3.1.0
      - httpcore==1.0.9
      - httptools==0.6.4
      - httpx==0.27.2
      - huggingface-hub==0.36.0
      - hydra-core==1.3.2
      - idna==3.11
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - iniconfig==2.3.0
      - interegular==0.3.3
      - intervaltree==3.1.0
      - iopath==0.1.10
      - ipykernel==6.30.1
      - ipython==8.37.0
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - jmespath==1.0.1
      - joblib==1.5.2
      - json5==0.12.1
      - jsonlines==4.0.0
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.9
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - kaitaistruct==0.11
      - kiwisolver==1.4.9
      - kornia==0.8.2
      - kornia-rs==0.1.10
      - lark==1.3.0
      - libclang==18.1.1
      - llvmlite==0.45.1
      - lm-format-enforcer==0.10.3
      - lxml==6.0.2
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markdown2==2.4.10
      - markupsafe==3.0.3
      - marshmallow==3.26.1
      - matplotlib==3.10.7
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mistune==3.1.4
      - ml-dtypes==0.5.3
      - more-itertools==10.1.0
      - mpmath==1.3.0
      - msgpack==1.1.1
      - multidict==6.7.0
      - multiprocess==0.70.16
      - mypy-extensions==1.1.0
      - namex==0.1.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - ninja==1.13.0
      - nltk==3.8.1
      - notebook-shim==0.2.4
      - num2words==0.5.14
      - numba==0.62.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==13.580.82
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - openai==1.39.0
      - opencv-python-headless==4.5.5.64
      - openpyxl==3.1.2
      - opt-einsum==3.4.0
      - optree==0.17.0
      - orjson==3.11.3
      - outlines==0.0.46
      - overrides==7.7.0
      - pandas==2.3.3
      - pandocfilters==1.5.1
      - parso==0.8.5
      - pdfminer-six==20250506
      - peft==0.11.1
      - pexpect==4.9.0
      - pillow==11.0.0
      - platformdirs==4.4.0
      - pluggy==1.6.0
      - polyfile-weave==0.5.7
      - portalocker==3.2.0
      - prometheus-client==0.23.1
      - prometheus-fastapi-instrumentator==7.1.0
      - prompt-toolkit==3.0.52
      - propcache==0.4.0
      - protobuf==5.29.5
      - psutil==7.1.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyairports==0.0.1
      - pyarrow==21.0.0
      - pycocoevalcap==1.2
      - pycocotools==2.0.10
      - pycountry==24.6.1
      - pycparser==2.23
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pydub==0.25.1
      - pygments==2.19.2
      - pynvml==13.0.1
      - pyparsing==3.2.5
      - pytest-asyncio==1.2.0
      - pytest-cov==7.0.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - python-json-logger==4.0.0
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - ray==2.49.2
      - referencing==0.36.2
      - regex==2025.11.3
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rich==14.1.0
      - rpds-py==0.27.1
      - ruff==0.13.3
      - s3transfer==0.14.0
      - sacrebleu==2.3.2
      - safehttpx==0.1.6
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - seaborn==0.13.0
      - semantic-version==2.10.0
      - send2trash==1.8.3
      - sentence-transformers==5.1.1
      - sentencepiece==0.1.99
      - sentry-sdk==2.40.0
      - setproctitle==1.3.7
      - setuptools==80.9.0
      - shellingham==1.5.4
      - shortuuid==1.0.11
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - socksio==1.0.0
      - sortedcontainers==2.4.0
      - soupsieve==2.8
      - stack-data==0.6.3
      - starlette==0.47.0
      - stdlib-list==0.11.1
      - submitit==1.5.3
      - sympy==1.14.0
      - tabulate==0.9.0
      - tenacity==9.1.2
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - termcolor==3.2.0
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - tiktoken==0.12.0
      - timm==0.9.10
      - tinycss2==1.4.0
      - tokenizers==0.22.1
      - tomlkit==0.13.3
      - torch==2.3.1
      - torchvision==0.18.1
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.57.1
      - triton==2.3.1
      - typer==0.19.2
      - types-python-dateutil==2.9.0.20250822
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - tzdata==2025.2
      - uri-template==1.3.0
      - urllib3==2.5.0
      - uvicorn==0.24.0.post1
      - uvloop==0.21.0
      - vllm==0.5.3.post1
      - vllm-flash-attn==2.5.9.post1
      - wandb==0.17.7
      - watchfiles==1.1.0
      - wcwidth==0.2.14
      - weave==0.52.16
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - websockets==15.0.1
      - werkzeug==3.1.3
      - wrapt==2.0.1
      - xformers==0.0.27
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: /u/siddique-d1/adib/ProAssist/.venv
