name: proassist
data_path: data/proassist/processed_data
# num_rows: -1  # Large enough to test real batching
# num_rows: 1  # Small test run
num_rows: 10  # Small test run
suffix: "_filtered"  # Use filtered files for faster results
frames_subdir: "frames"
datasets:
  - assembly101
  # - ego4d
  # - egoexolearn
  # - epickitchens
  # - holoassist
  # - wtag
